// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#include "../ui.h"

lv_obj_t * ui_GameScreen = NULL;
lv_obj_t * ui_GameLabelPickGame = NULL;
lv_obj_t * ui_GameContainerBackground = NULL;
lv_obj_t * ui_GameContainerSnakeGame = NULL;
lv_obj_t * ui_GameLabelSnakeGameName = NULL;
lv_obj_t * ui_GameImageSnake = NULL;
lv_obj_t * ui_GameContainerReactionGame = NULL;
lv_obj_t * ui_GameLabelReactionGameName = NULL;
lv_obj_t * ui_GameImageReaction = NULL;
lv_obj_t * ui_GameContainerWhackGame = NULL;
lv_obj_t * ui_GameLabelWhackGameName = NULL;
lv_obj_t * ui_GameImageWhack = NULL;
lv_obj_t * ui_GameContainerNonogramGame = NULL;
lv_obj_t * ui_GameLabelNonogramGameName = NULL;
lv_obj_t * ui_GameImageNonogram = NULL;
// event funtions

// build funtions

void ui_GameScreen_screen_init(void)
{
    ui_GameScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_GameScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GameScreen, lv_color_hex(0xF4F3EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameLabelPickGame = lv_label_create(ui_GameScreen);
    lv_obj_set_width(ui_GameLabelPickGame, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameLabelPickGame, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GameLabelPickGame, 40);
    lv_obj_set_y(ui_GameLabelPickGame, 10);
    lv_label_set_text(ui_GameLabelPickGame, "Pick a game");
    lv_obj_set_style_text_font(ui_GameLabelPickGame, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameContainerBackground = lv_obj_create(ui_GameScreen);
    lv_obj_remove_style_all(ui_GameContainerBackground);
    lv_obj_set_width(ui_GameContainerBackground, 420);
    lv_obj_set_height(ui_GameContainerBackground, 430);
    lv_obj_set_x(ui_GameContainerBackground, 0);
    lv_obj_set_y(ui_GameContainerBackground, 50);
    lv_obj_set_align(ui_GameContainerBackground, LV_ALIGN_TOP_MID);

    ui_GameContainerSnakeGame = lv_obj_create(ui_GameContainerBackground);
    lv_obj_remove_style_all(ui_GameContainerSnakeGame);
    lv_obj_set_width(ui_GameContainerSnakeGame, 180);
    lv_obj_set_height(ui_GameContainerSnakeGame, 200);
    lv_obj_set_x(ui_GameContainerSnakeGame, 20);
    lv_obj_set_y(ui_GameContainerSnakeGame, 20);
    lv_obj_remove_flag(ui_GameContainerSnakeGame, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GameContainerSnakeGame, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GameContainerSnakeGame, lv_color_hex(0xACE2B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameContainerSnakeGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GameContainerSnakeGame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GameContainerSnakeGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GameContainerSnakeGame, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GameContainerSnakeGame, lv_color_hex(0x599165), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GameContainerSnakeGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GameContainerSnakeGame, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GameContainerSnakeGame, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_GameContainerSnakeGame, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_GameContainerSnakeGame, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameLabelSnakeGameName = lv_label_create(ui_GameContainerSnakeGame);
    lv_obj_set_width(ui_GameLabelSnakeGameName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameLabelSnakeGameName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GameLabelSnakeGameName, 20);
    lv_obj_set_y(ui_GameLabelSnakeGameName, -20);
    lv_obj_set_align(ui_GameLabelSnakeGameName, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_GameLabelSnakeGameName, "Snack");
    lv_obj_set_style_text_font(ui_GameLabelSnakeGameName, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameImageSnake = lv_image_create(ui_GameContainerSnakeGame);
    lv_image_set_src(ui_GameImageSnake, &ui_img_snake_png);
    lv_obj_set_width(ui_GameImageSnake, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameImageSnake, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GameImageSnake, -5);
    lv_obj_set_y(ui_GameImageSnake, 10);
    lv_obj_set_align(ui_GameImageSnake, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_GameImageSnake, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GameContainerReactionGame = lv_obj_create(ui_GameContainerBackground);
    lv_obj_remove_style_all(ui_GameContainerReactionGame);
    lv_obj_set_width(ui_GameContainerReactionGame, 180);
    lv_obj_set_height(ui_GameContainerReactionGame, 200);
    lv_obj_set_x(ui_GameContainerReactionGame, 220);
    lv_obj_set_y(ui_GameContainerReactionGame, 20);
    lv_obj_remove_flag(ui_GameContainerReactionGame, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GameContainerReactionGame, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GameContainerReactionGame, lv_color_hex(0xEF8670), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameContainerReactionGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GameContainerReactionGame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GameContainerReactionGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GameContainerReactionGame, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GameContainerReactionGame, lv_color_hex(0x81807B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GameContainerReactionGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GameContainerReactionGame, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GameContainerReactionGame, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_GameContainerReactionGame, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_GameContainerReactionGame, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameLabelReactionGameName = lv_label_create(ui_GameContainerReactionGame);
    lv_obj_set_width(ui_GameLabelReactionGameName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameLabelReactionGameName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GameLabelReactionGameName, 20);
    lv_obj_set_y(ui_GameLabelReactionGameName, -20);
    lv_obj_set_align(ui_GameLabelReactionGameName, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_GameLabelReactionGameName, "Reaction");
    lv_obj_set_style_text_font(ui_GameLabelReactionGameName, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameImageReaction = lv_image_create(ui_GameContainerReactionGame);
    lv_image_set_src(ui_GameImageReaction, &ui_img_reaction_png);
    lv_obj_set_width(ui_GameImageReaction, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameImageReaction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GameImageReaction, -5);
    lv_obj_set_y(ui_GameImageReaction, 10);
    lv_obj_set_align(ui_GameImageReaction, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_GameImageReaction, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GameContainerWhackGame = lv_obj_create(ui_GameContainerBackground);
    lv_obj_remove_style_all(ui_GameContainerWhackGame);
    lv_obj_set_width(ui_GameContainerWhackGame, 180);
    lv_obj_set_height(ui_GameContainerWhackGame, 200);
    lv_obj_set_x(ui_GameContainerWhackGame, 20);
    lv_obj_set_y(ui_GameContainerWhackGame, 240);
    lv_obj_remove_flag(ui_GameContainerWhackGame, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GameContainerWhackGame, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GameContainerWhackGame, lv_color_hex(0x87CE92), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameContainerWhackGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GameContainerWhackGame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GameContainerWhackGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GameContainerWhackGame, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GameContainerWhackGame, lv_color_hex(0x80807B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GameContainerWhackGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GameContainerWhackGame, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GameContainerWhackGame, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_GameContainerWhackGame, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_GameContainerWhackGame, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameLabelWhackGameName = lv_label_create(ui_GameContainerWhackGame);
    lv_obj_set_width(ui_GameLabelWhackGameName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameLabelWhackGameName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GameLabelWhackGameName, 20);
    lv_obj_set_y(ui_GameLabelWhackGameName, -20);
    lv_obj_set_align(ui_GameLabelWhackGameName, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_GameLabelWhackGameName, "Whack");
    lv_obj_set_style_text_font(ui_GameLabelWhackGameName, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameImageWhack = lv_image_create(ui_GameContainerWhackGame);
    lv_image_set_src(ui_GameImageWhack, &ui_img_whack_png);
    lv_obj_set_width(ui_GameImageWhack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameImageWhack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GameImageWhack, -5);
    lv_obj_set_y(ui_GameImageWhack, 10);
    lv_obj_set_align(ui_GameImageWhack, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_GameImageWhack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GameContainerNonogramGame = lv_obj_create(ui_GameContainerBackground);
    lv_obj_remove_style_all(ui_GameContainerNonogramGame);
    lv_obj_set_width(ui_GameContainerNonogramGame, 180);
    lv_obj_set_height(ui_GameContainerNonogramGame, 200);
    lv_obj_set_x(ui_GameContainerNonogramGame, 220);
    lv_obj_set_y(ui_GameContainerNonogramGame, 240);
    lv_obj_remove_flag(ui_GameContainerNonogramGame, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GameContainerNonogramGame, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GameContainerNonogramGame, lv_color_hex(0xB28F87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GameContainerNonogramGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GameContainerNonogramGame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GameContainerNonogramGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GameContainerNonogramGame, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GameContainerNonogramGame, lv_color_hex(0x81807B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GameContainerNonogramGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_GameContainerNonogramGame, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_GameContainerNonogramGame, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_GameContainerNonogramGame, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_GameContainerNonogramGame, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameLabelNonogramGameName = lv_label_create(ui_GameContainerNonogramGame);
    lv_obj_set_width(ui_GameLabelNonogramGameName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameLabelNonogramGameName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GameLabelNonogramGameName, 20);
    lv_obj_set_y(ui_GameLabelNonogramGameName, -20);
    lv_obj_set_align(ui_GameLabelNonogramGameName, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_GameLabelNonogramGameName, "Nonogram");
    lv_obj_set_style_text_font(ui_GameLabelNonogramGameName, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GameImageNonogram = lv_image_create(ui_GameContainerNonogramGame);
    lv_image_set_src(ui_GameImageNonogram, &ui_img_nonogram_png);
    lv_obj_set_width(ui_GameImageNonogram, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GameImageNonogram, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GameImageNonogram, -5);
    lv_obj_set_y(ui_GameImageNonogram, 10);
    lv_obj_set_align(ui_GameImageNonogram, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_GameImageNonogram, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_GameScreen_screen_destroy(void)
{
    if(ui_GameScreen) lv_obj_del(ui_GameScreen);

    // NULL screen variables
    ui_GameScreen = NULL;
    ui_GameLabelPickGame = NULL;
    ui_GameContainerBackground = NULL;
    ui_GameContainerSnakeGame = NULL;
    ui_GameLabelSnakeGameName = NULL;
    ui_GameImageSnake = NULL;
    ui_GameContainerReactionGame = NULL;
    ui_GameLabelReactionGameName = NULL;
    ui_GameImageReaction = NULL;
    ui_GameContainerWhackGame = NULL;
    ui_GameLabelWhackGameName = NULL;
    ui_GameImageWhack = NULL;
    ui_GameContainerNonogramGame = NULL;
    ui_GameLabelNonogramGameName = NULL;
    ui_GameImageNonogram = NULL;

}
