// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#ifndef UI_GAMESCREEN_H
#define UI_GAMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GameScreen
extern void ui_GameScreen_screen_init(void);
extern void ui_GameScreen_screen_destroy(void);
extern lv_obj_t * ui_GameScreen;
extern lv_obj_t * ui_GameLabelPickGame;
extern lv_obj_t * ui_GameContainerBackground;
extern lv_obj_t * ui_GameContainerSnakeGame;
extern lv_obj_t * ui_GameLabelSnakeGameName;
extern lv_obj_t * ui_GameImageSnake;
extern lv_obj_t * ui_GameContainerReactionGame;
extern lv_obj_t * ui_GameLabelReactionGameName;
extern lv_obj_t * ui_GameImageReaction;
extern lv_obj_t * ui_GameContainerWhackGame;
extern lv_obj_t * ui_GameLabelWhackGameName;
extern lv_obj_t * ui_GameImageWhack;
extern lv_obj_t * ui_GameContainerNonogramGame;
extern lv_obj_t * ui_GameLabelNonogramGameName;
extern lv_obj_t * ui_GameImageNonogram;
extern lv_obj_t * ui_GameContainerJumpPrinceGame;
extern lv_obj_t * ui_GameLabelJumpPrinceGameName;
extern lv_obj_t * ui_GameImageJumpPrince;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

