// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#ifndef UI_NONOGRAMSCREEN_H
#define UI_NONOGRAMSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_NonogramScreen
extern void ui_NonogramScreen_screen_init(void);
extern void ui_NonogramScreen_screen_destroy(void);
extern lv_obj_t * ui_NonogramScreen;
extern lv_obj_t * ui_NonogramContainerToolMenu;
extern lv_obj_t * ui_NonogramImageToolMenu;
extern lv_obj_t * ui_NonogramContainerGameInfo;
extern lv_obj_t * ui_NonogramDropdownGameDifficulty;
extern lv_obj_t * ui_NonogramContainerGameRound;
extern lv_obj_t * ui_NonogramLabelGameRound;
extern lv_obj_t * ui_NonogramLabelGameRoundData;
extern lv_obj_t * ui_NonogramContainerGameTime;
extern lv_obj_t * ui_NonogramLabelGameTime;
extern lv_obj_t * ui_NonogramLabelGameTimeData;
extern lv_obj_t * ui_NonogramContainerPlayAreaBackground;
extern lv_obj_t * ui_NonogramContainerPlayArea;
extern lv_obj_t * ui_NonogramContainerPaintArea;
extern lv_obj_t * ui_NonogramContainerTools;
extern lv_obj_t * ui_NonogramContainerToolExit;
extern lv_obj_t * ui_NonogramImageToolExit;
extern lv_obj_t * ui_NonogramContainerToolQuestion;
extern lv_obj_t * ui_NonogramImageToolQuestion;
extern lv_obj_t * ui_NonogramContainerToolMusic;
extern lv_obj_t * ui_NonogramImageToolMusic;
extern lv_obj_t * ui_NonogramContainerToolRestart;
extern lv_obj_t * ui_NonogramImageToolRestart;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

