// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#include "../ui.h"

lv_obj_t * ui_NonogramScreen = NULL;
lv_obj_t * ui_NonogramContainerToolMenu = NULL;
lv_obj_t * ui_NonogramImageToolMenu = NULL;
lv_obj_t * ui_NonogramContainerGameInfo = NULL;
lv_obj_t * ui_NonogramDropdownGameDifficulty = NULL;
lv_obj_t * ui_NonogramContainerGameRound = NULL;
lv_obj_t * ui_NonogramLabelGameRound = NULL;
lv_obj_t * ui_NonogramLabelGameRoundData = NULL;
lv_obj_t * ui_NonogramContainerGameTime = NULL;
lv_obj_t * ui_NonogramLabelGameTime = NULL;
lv_obj_t * ui_NonogramLabelGameTimeData = NULL;
lv_obj_t * ui_NonogramContainerPlayAreaBackground = NULL;
lv_obj_t * ui_NonogramContainerPlayArea = NULL;
lv_obj_t * ui_NonogramContainerPaintArea = NULL;
lv_obj_t * ui_NonogramContainerTools = NULL;
lv_obj_t * ui_NonogramContainerToolExit = NULL;
lv_obj_t * ui_NonogramImageToolExit = NULL;
lv_obj_t * ui_NonogramContainerToolQuestion = NULL;
lv_obj_t * ui_NonogramImageToolQuestion = NULL;
lv_obj_t * ui_NonogramContainerToolMusic = NULL;
lv_obj_t * ui_NonogramImageToolMusic = NULL;
lv_obj_t * ui_NonogramContainerToolRestart = NULL;
lv_obj_t * ui_NonogramImageToolRestart = NULL;
// event funtions

// build funtions

void ui_NonogramScreen_screen_init(void)
{
    ui_NonogramScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_NonogramScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NonogramScreen, lv_color_hex(0xE6EEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramContainerToolMenu = lv_obj_create(ui_NonogramScreen);
    lv_obj_remove_style_all(ui_NonogramContainerToolMenu);
    lv_obj_set_width(ui_NonogramContainerToolMenu, 50);
    lv_obj_set_height(ui_NonogramContainerToolMenu, 50);
    lv_obj_set_x(ui_NonogramContainerToolMenu, 20);
    lv_obj_set_y(ui_NonogramContainerToolMenu, 5);
    lv_obj_remove_flag(ui_NonogramContainerToolMenu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NonogramContainerToolMenu, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NonogramContainerToolMenu, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramContainerToolMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramContainerToolMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NonogramContainerToolMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NonogramContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NonogramContainerToolMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NonogramContainerToolMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_NonogramContainerToolMenu, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_NonogramContainerToolMenu, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramImageToolMenu = lv_image_create(ui_NonogramContainerToolMenu);
    lv_image_set_src(ui_NonogramImageToolMenu, &ui_img_menu_png);
    lv_obj_set_width(ui_NonogramImageToolMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NonogramImageToolMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NonogramImageToolMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NonogramImageToolMenu, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_NonogramImageToolMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NonogramContainerGameInfo = lv_obj_create(ui_NonogramScreen);
    lv_obj_remove_style_all(ui_NonogramContainerGameInfo);
    lv_obj_set_width(ui_NonogramContainerGameInfo, 400);
    lv_obj_set_height(ui_NonogramContainerGameInfo, 60);
    lv_obj_set_x(ui_NonogramContainerGameInfo, 30);
    lv_obj_set_y(ui_NonogramContainerGameInfo, 0);
    lv_obj_set_align(ui_NonogramContainerGameInfo, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_NonogramContainerGameInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NonogramDropdownGameDifficulty = lv_dropdown_create(ui_NonogramContainerGameInfo);
    lv_dropdown_set_options(ui_NonogramDropdownGameDifficulty, "Easy\nNormal\nHard");
    lv_obj_set_width(ui_NonogramDropdownGameDifficulty, 120);
    lv_obj_set_height(ui_NonogramDropdownGameDifficulty, 50);
    lv_obj_set_x(ui_NonogramDropdownGameDifficulty, -130);
    lv_obj_set_y(ui_NonogramDropdownGameDifficulty, 0);
    lv_obj_set_align(ui_NonogramDropdownGameDifficulty, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NonogramDropdownGameDifficulty, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_NonogramDropdownGameDifficulty, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_NonogramDropdownGameDifficulty, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NonogramDropdownGameDifficulty, lv_color_hex(0xFFFAF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramDropdownGameDifficulty, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramDropdownGameDifficulty, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramDropdownGameDifficulty, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramDropdownGameDifficulty, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_NonogramDropdownGameDifficulty, &lv_font_montserrat_18,
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_NonogramContainerGameRound = lv_obj_create(ui_NonogramContainerGameInfo);
    lv_obj_remove_style_all(ui_NonogramContainerGameRound);
    lv_obj_set_width(ui_NonogramContainerGameRound, 120);
    lv_obj_set_height(ui_NonogramContainerGameRound, 50);
    lv_obj_set_align(ui_NonogramContainerGameRound, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_NonogramContainerGameRound, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NonogramContainerGameRound, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NonogramContainerGameRound, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramContainerGameRound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramContainerGameRound, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramContainerGameRound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramContainerGameRound, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramLabelGameRound = lv_label_create(ui_NonogramContainerGameRound);
    lv_obj_set_width(ui_NonogramLabelGameRound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NonogramLabelGameRound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NonogramLabelGameRound, 0);
    lv_obj_set_y(ui_NonogramLabelGameRound, -10);
    lv_obj_set_align(ui_NonogramLabelGameRound, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NonogramLabelGameRound, "ROUND");
    lv_obj_set_style_text_font(ui_NonogramLabelGameRound, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramLabelGameRoundData = lv_label_create(ui_NonogramContainerGameRound);
    lv_obj_set_width(ui_NonogramLabelGameRoundData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NonogramLabelGameRoundData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NonogramLabelGameRoundData, 0);
    lv_obj_set_y(ui_NonogramLabelGameRoundData, 10);
    lv_obj_set_align(ui_NonogramLabelGameRoundData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NonogramLabelGameRoundData, "1/5");
    lv_obj_set_style_text_font(ui_NonogramLabelGameRoundData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramContainerGameTime = lv_obj_create(ui_NonogramContainerGameInfo);
    lv_obj_remove_style_all(ui_NonogramContainerGameTime);
    lv_obj_set_width(ui_NonogramContainerGameTime, 120);
    lv_obj_set_height(ui_NonogramContainerGameTime, 50);
    lv_obj_set_x(ui_NonogramContainerGameTime, 130);
    lv_obj_set_y(ui_NonogramContainerGameTime, 0);
    lv_obj_set_align(ui_NonogramContainerGameTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_NonogramContainerGameTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NonogramContainerGameTime, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NonogramContainerGameTime, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramContainerGameTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramContainerGameTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramContainerGameTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramContainerGameTime, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramLabelGameTime = lv_label_create(ui_NonogramContainerGameTime);
    lv_obj_set_width(ui_NonogramLabelGameTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NonogramLabelGameTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NonogramLabelGameTime, 0);
    lv_obj_set_y(ui_NonogramLabelGameTime, -10);
    lv_obj_set_align(ui_NonogramLabelGameTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NonogramLabelGameTime, "TIME");
    lv_obj_set_style_text_font(ui_NonogramLabelGameTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramLabelGameTimeData = lv_label_create(ui_NonogramContainerGameTime);
    lv_obj_set_width(ui_NonogramLabelGameTimeData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NonogramLabelGameTimeData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NonogramLabelGameTimeData, 0);
    lv_obj_set_y(ui_NonogramLabelGameTimeData, 10);
    lv_obj_set_align(ui_NonogramLabelGameTimeData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NonogramLabelGameTimeData, "0s");
    lv_obj_set_style_text_font(ui_NonogramLabelGameTimeData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramContainerPlayAreaBackground = lv_obj_create(ui_NonogramScreen);
    lv_obj_remove_style_all(ui_NonogramContainerPlayAreaBackground);
    lv_obj_set_width(ui_NonogramContainerPlayAreaBackground, 400);
    lv_obj_set_height(ui_NonogramContainerPlayAreaBackground, 400);
    lv_obj_set_x(ui_NonogramContainerPlayAreaBackground, 0);
    lv_obj_set_y(ui_NonogramContainerPlayAreaBackground, 30);
    lv_obj_set_align(ui_NonogramContainerPlayAreaBackground, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_NonogramContainerPlayAreaBackground,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NonogramContainerPlayAreaBackground, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NonogramContainerPlayAreaBackground, lv_color_hex(0xE3F3D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramContainerPlayAreaBackground, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramContainerPlayAreaBackground, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NonogramContainerPlayAreaBackground, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NonogramContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NonogramContainerPlayAreaBackground, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NonogramContainerPlayAreaBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_NonogramContainerPlayAreaBackground, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_NonogramContainerPlayAreaBackground, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramContainerPlayArea = lv_obj_create(ui_NonogramContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_NonogramContainerPlayArea);
    lv_obj_set_width(ui_NonogramContainerPlayArea, 375);
    lv_obj_set_height(ui_NonogramContainerPlayArea, 375);
    lv_obj_set_align(ui_NonogramContainerPlayArea, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_NonogramContainerPlayArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NonogramContainerPaintArea = lv_obj_create(ui_NonogramContainerPlayArea);
    lv_obj_remove_style_all(ui_NonogramContainerPaintArea);
    lv_obj_set_width(ui_NonogramContainerPaintArea, 300);
    lv_obj_set_height(ui_NonogramContainerPaintArea, 300);
    lv_obj_set_x(ui_NonogramContainerPaintArea, 0);
    lv_obj_set_y(ui_NonogramContainerPaintArea, 0);
    lv_obj_set_align(ui_NonogramContainerPaintArea, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_NonogramContainerPaintArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NonogramContainerPaintArea, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramContainerPaintArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramContainerPaintArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramContainerPaintArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramContainerTools = lv_obj_create(ui_NonogramScreen);
    lv_obj_remove_style_all(ui_NonogramContainerTools);
    lv_obj_set_width(ui_NonogramContainerTools, 80);
    lv_obj_set_height(ui_NonogramContainerTools, 480);
    lv_obj_set_x(ui_NonogramContainerTools, -10);
    lv_obj_set_y(ui_NonogramContainerTools, 0);
    lv_obj_add_flag(ui_NonogramContainerTools, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_NonogramContainerTools, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NonogramContainerTools, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NonogramContainerTools, lv_color_hex(0xB3DFA7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramContainerTools, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramContainerTools, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NonogramContainerTools, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NonogramContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NonogramContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NonogramContainerTools, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_NonogramContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_NonogramContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramContainerToolExit = lv_obj_create(ui_NonogramContainerTools);
    lv_obj_remove_style_all(ui_NonogramContainerToolExit);
    lv_obj_set_width(ui_NonogramContainerToolExit, 50);
    lv_obj_set_height(ui_NonogramContainerToolExit, 50);
    lv_obj_set_x(ui_NonogramContainerToolExit, 5);
    lv_obj_set_y(ui_NonogramContainerToolExit, 20);
    lv_obj_set_align(ui_NonogramContainerToolExit, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_NonogramContainerToolExit, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NonogramContainerToolExit, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NonogramContainerToolExit, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramContainerToolExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramContainerToolExit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NonogramContainerToolExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NonogramContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NonogramContainerToolExit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NonogramContainerToolExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_NonogramContainerToolExit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_NonogramContainerToolExit, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramImageToolExit = lv_image_create(ui_NonogramContainerToolExit);
    lv_image_set_src(ui_NonogramImageToolExit, &ui_img_exit_png);
    lv_obj_set_width(ui_NonogramImageToolExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NonogramImageToolExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NonogramImageToolExit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NonogramImageToolExit, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_NonogramImageToolExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NonogramContainerToolQuestion = lv_obj_create(ui_NonogramContainerTools);
    lv_obj_remove_style_all(ui_NonogramContainerToolQuestion);
    lv_obj_set_width(ui_NonogramContainerToolQuestion, 50);
    lv_obj_set_height(ui_NonogramContainerToolQuestion, 50);
    lv_obj_set_x(ui_NonogramContainerToolQuestion, 5);
    lv_obj_set_y(ui_NonogramContainerToolQuestion, 100);
    lv_obj_set_align(ui_NonogramContainerToolQuestion, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_NonogramContainerToolQuestion, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NonogramContainerToolQuestion, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NonogramContainerToolQuestion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramContainerToolQuestion, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramContainerToolQuestion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NonogramContainerToolQuestion, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NonogramContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NonogramContainerToolQuestion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NonogramContainerToolQuestion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_NonogramContainerToolQuestion, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_NonogramContainerToolQuestion, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramImageToolQuestion = lv_image_create(ui_NonogramContainerToolQuestion);
    lv_image_set_src(ui_NonogramImageToolQuestion, &ui_img_question_png);
    lv_obj_set_width(ui_NonogramImageToolQuestion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NonogramImageToolQuestion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NonogramImageToolQuestion, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NonogramImageToolQuestion, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_NonogramImageToolQuestion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NonogramContainerToolMusic = lv_obj_create(ui_NonogramContainerTools);
    lv_obj_remove_style_all(ui_NonogramContainerToolMusic);
    lv_obj_set_width(ui_NonogramContainerToolMusic, 50);
    lv_obj_set_height(ui_NonogramContainerToolMusic, 50);
    lv_obj_set_x(ui_NonogramContainerToolMusic, 5);
    lv_obj_set_y(ui_NonogramContainerToolMusic, 180);
    lv_obj_set_align(ui_NonogramContainerToolMusic, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_NonogramContainerToolMusic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NonogramContainerToolMusic, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NonogramContainerToolMusic, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramContainerToolMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramContainerToolMusic, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NonogramContainerToolMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NonogramContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NonogramContainerToolMusic, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NonogramContainerToolMusic, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_NonogramContainerToolMusic, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_NonogramContainerToolMusic, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramImageToolMusic = lv_image_create(ui_NonogramContainerToolMusic);
    lv_image_set_src(ui_NonogramImageToolMusic, &ui_img_music_png);
    lv_obj_set_width(ui_NonogramImageToolMusic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NonogramImageToolMusic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NonogramImageToolMusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NonogramImageToolMusic, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_NonogramImageToolMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NonogramContainerToolRestart = lv_obj_create(ui_NonogramContainerTools);
    lv_obj_remove_style_all(ui_NonogramContainerToolRestart);
    lv_obj_set_width(ui_NonogramContainerToolRestart, 50);
    lv_obj_set_height(ui_NonogramContainerToolRestart, 50);
    lv_obj_set_x(ui_NonogramContainerToolRestart, 5);
    lv_obj_set_y(ui_NonogramContainerToolRestart, 260);
    lv_obj_set_align(ui_NonogramContainerToolRestart, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_NonogramContainerToolRestart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NonogramContainerToolRestart, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NonogramContainerToolRestart, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NonogramContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NonogramContainerToolRestart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NonogramContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NonogramContainerToolRestart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NonogramContainerToolRestart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NonogramContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NonogramContainerToolRestart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NonogramContainerToolRestart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_NonogramContainerToolRestart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_NonogramContainerToolRestart, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NonogramImageToolRestart = lv_image_create(ui_NonogramContainerToolRestart);
    lv_image_set_src(ui_NonogramImageToolRestart, &ui_img_restart_png);
    lv_obj_set_width(ui_NonogramImageToolRestart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NonogramImageToolRestart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NonogramImageToolRestart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NonogramImageToolRestart, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_NonogramImageToolRestart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_NonogramScreen_screen_destroy(void)
{
    if(ui_NonogramScreen) lv_obj_del(ui_NonogramScreen);

    // NULL screen variables
    ui_NonogramScreen = NULL;
    ui_NonogramContainerToolMenu = NULL;
    ui_NonogramImageToolMenu = NULL;
    ui_NonogramContainerGameInfo = NULL;
    ui_NonogramDropdownGameDifficulty = NULL;
    ui_NonogramContainerGameRound = NULL;
    ui_NonogramLabelGameRound = NULL;
    ui_NonogramLabelGameRoundData = NULL;
    ui_NonogramContainerGameTime = NULL;
    ui_NonogramLabelGameTime = NULL;
    ui_NonogramLabelGameTimeData = NULL;
    ui_NonogramContainerPlayAreaBackground = NULL;
    ui_NonogramContainerPlayArea = NULL;
    ui_NonogramContainerPaintArea = NULL;
    ui_NonogramContainerTools = NULL;
    ui_NonogramContainerToolExit = NULL;
    ui_NonogramImageToolExit = NULL;
    ui_NonogramContainerToolQuestion = NULL;
    ui_NonogramImageToolQuestion = NULL;
    ui_NonogramContainerToolMusic = NULL;
    ui_NonogramImageToolMusic = NULL;
    ui_NonogramContainerToolRestart = NULL;
    ui_NonogramImageToolRestart = NULL;

}
