// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#ifndef UI_RAPIDTAPSCREEN_H
#define UI_RAPIDTAPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ReactionScreen
extern void ui_ReactionScreen_screen_init(void);
extern void ui_ReactionScreen_screen_destroy(void);
extern lv_obj_t * ui_ReactionScreen;
extern lv_obj_t * ui_ReactionContainerToolMenu;
extern lv_obj_t * ui_ReactionImageToolMenu;
extern lv_obj_t * ui_ReactionContainerGameInfo;
extern lv_obj_t * ui_ReactionContainerGameRound;
extern lv_obj_t * ui_ReactionLabelGameRound;
extern lv_obj_t * ui_ReactionLabelGameRoundData;
extern lv_obj_t * ui_ReactionContainerGameBest;
extern lv_obj_t * ui_ReactionLabelGameBest;
extern lv_obj_t * ui_ReactionLabelGameBestData;
extern lv_obj_t * ui_ReactionContainerGameFalse;
extern lv_obj_t * ui_ReactionLabelGameFalse;
extern lv_obj_t * ui_ReactionLabelGameFalseData;
extern lv_obj_t * ui_ReactionContainerPlayAreaBackground;
extern lv_obj_t * ui_ReactionLabelPlayAreaMainTitle;
extern lv_obj_t * ui_ReactionLabelPlayAreaSubtitle;
extern lv_obj_t * ui_ReactionLabelPlayAreaRound;
extern lv_obj_t * ui_ReactionContainerTools;
extern lv_obj_t * ui_ReactionContainerToolExit;
extern lv_obj_t * ui_ReactionImageToolExit;
extern lv_obj_t * ui_ReactionContainerToolQuestion;
extern lv_obj_t * ui_ReactionImageToolQuestion;
extern lv_obj_t * ui_ReactionContainerToolMusic;
extern lv_obj_t * ui_ReactionImageToolMusic;
extern lv_obj_t * ui_ReactionContainerToolRestart;
extern lv_obj_t * ui_ReactionImageToolRestart;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

