// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#include "../ui.h"

lv_obj_t * ui_ReactionScreen = NULL;
lv_obj_t * ui_ReactionContainerToolMenu = NULL;
lv_obj_t * ui_ReactionImageToolMenu = NULL;
lv_obj_t * ui_ReactionContainerGameInfo = NULL;
lv_obj_t * ui_ReactionContainerGameRound = NULL;
lv_obj_t * ui_ReactionLabelGameRound = NULL;
lv_obj_t * ui_ReactionLabelGameRoundData = NULL;
lv_obj_t * ui_ReactionContainerGameBest = NULL;
lv_obj_t * ui_ReactionLabelGameBest = NULL;
lv_obj_t * ui_ReactionLabelGameBestData = NULL;
lv_obj_t * ui_ReactionContainerGameFalse = NULL;
lv_obj_t * ui_ReactionLabelGameFalse = NULL;
lv_obj_t * ui_ReactionLabelGameFalseData = NULL;
lv_obj_t * ui_ReactionContainerPlayAreaBackground = NULL;
lv_obj_t * ui_ReactionLabelPlayAreaMainTitle = NULL;
lv_obj_t * ui_ReactionLabelPlayAreaSubtitle = NULL;
lv_obj_t * ui_ReactionLabelPlayAreaRound = NULL;
lv_obj_t * ui_ReactionContainerTools = NULL;
lv_obj_t * ui_ReactionContainerToolExit = NULL;
lv_obj_t * ui_ReactionImageToolExit = NULL;
lv_obj_t * ui_ReactionContainerToolQuestion = NULL;
lv_obj_t * ui_ReactionImageToolQuestion = NULL;
lv_obj_t * ui_ReactionContainerToolMusic = NULL;
lv_obj_t * ui_ReactionImageToolMusic = NULL;
lv_obj_t * ui_ReactionContainerToolRestart = NULL;
lv_obj_t * ui_ReactionImageToolRestart = NULL;
// event funtions

// build funtions

void ui_ReactionScreen_screen_init(void)
{
    ui_ReactionScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ReactionScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ReactionScreen, lv_color_hex(0xF3EDCD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionContainerToolMenu = lv_obj_create(ui_ReactionScreen);
    lv_obj_remove_style_all(ui_ReactionContainerToolMenu);
    lv_obj_set_width(ui_ReactionContainerToolMenu, 50);
    lv_obj_set_height(ui_ReactionContainerToolMenu, 50);
    lv_obj_set_x(ui_ReactionContainerToolMenu, 20);
    lv_obj_set_y(ui_ReactionContainerToolMenu, 5);
    lv_obj_remove_flag(ui_ReactionContainerToolMenu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReactionContainerToolMenu, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReactionContainerToolMenu, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReactionContainerToolMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReactionContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReactionContainerToolMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ReactionContainerToolMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ReactionContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ReactionContainerToolMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ReactionContainerToolMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ReactionContainerToolMenu, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ReactionContainerToolMenu, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionImageToolMenu = lv_image_create(ui_ReactionContainerToolMenu);
    lv_image_set_src(ui_ReactionImageToolMenu, &ui_img_menu_png);
    lv_obj_set_width(ui_ReactionImageToolMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionImageToolMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReactionImageToolMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReactionImageToolMenu, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ReactionImageToolMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ReactionContainerGameInfo = lv_obj_create(ui_ReactionScreen);
    lv_obj_remove_style_all(ui_ReactionContainerGameInfo);
    lv_obj_set_width(ui_ReactionContainerGameInfo, 400);
    lv_obj_set_height(ui_ReactionContainerGameInfo, 60);
    lv_obj_set_x(ui_ReactionContainerGameInfo, 30);
    lv_obj_set_y(ui_ReactionContainerGameInfo, 0);
    lv_obj_set_align(ui_ReactionContainerGameInfo, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ReactionContainerGameInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ReactionContainerGameRound = lv_obj_create(ui_ReactionContainerGameInfo);
    lv_obj_remove_style_all(ui_ReactionContainerGameRound);
    lv_obj_set_width(ui_ReactionContainerGameRound, 120);
    lv_obj_set_height(ui_ReactionContainerGameRound, 50);
    lv_obj_set_x(ui_ReactionContainerGameRound, -130);
    lv_obj_set_y(ui_ReactionContainerGameRound, 0);
    lv_obj_set_align(ui_ReactionContainerGameRound, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReactionContainerGameRound, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReactionContainerGameRound, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReactionContainerGameRound, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionContainerGameRound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReactionContainerGameRound, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReactionContainerGameRound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReactionContainerGameRound, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionLabelGameRound = lv_label_create(ui_ReactionContainerGameRound);
    lv_obj_set_width(ui_ReactionLabelGameRound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionLabelGameRound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReactionLabelGameRound, 0);
    lv_obj_set_y(ui_ReactionLabelGameRound, -10);
    lv_obj_set_align(ui_ReactionLabelGameRound, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReactionLabelGameRound, "ROUND");
    lv_obj_set_style_text_font(ui_ReactionLabelGameRound, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionLabelGameRoundData = lv_label_create(ui_ReactionContainerGameRound);
    lv_obj_set_width(ui_ReactionLabelGameRoundData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionLabelGameRoundData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReactionLabelGameRoundData, 0);
    lv_obj_set_y(ui_ReactionLabelGameRoundData, 10);
    lv_obj_set_align(ui_ReactionLabelGameRoundData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReactionLabelGameRoundData, "1/5");
    lv_obj_set_style_text_font(ui_ReactionLabelGameRoundData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionContainerGameBest = lv_obj_create(ui_ReactionContainerGameInfo);
    lv_obj_remove_style_all(ui_ReactionContainerGameBest);
    lv_obj_set_width(ui_ReactionContainerGameBest, 120);
    lv_obj_set_height(ui_ReactionContainerGameBest, 50);
    lv_obj_set_align(ui_ReactionContainerGameBest, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReactionContainerGameBest, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReactionContainerGameBest, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReactionContainerGameBest, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionContainerGameBest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReactionContainerGameBest, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReactionContainerGameBest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReactionContainerGameBest, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionLabelGameBest = lv_label_create(ui_ReactionContainerGameBest);
    lv_obj_set_width(ui_ReactionLabelGameBest, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionLabelGameBest, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReactionLabelGameBest, 0);
    lv_obj_set_y(ui_ReactionLabelGameBest, -10);
    lv_obj_set_align(ui_ReactionLabelGameBest, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReactionLabelGameBest, "BEST");
    lv_obj_set_style_text_font(ui_ReactionLabelGameBest, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionLabelGameBestData = lv_label_create(ui_ReactionContainerGameBest);
    lv_obj_set_width(ui_ReactionLabelGameBestData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionLabelGameBestData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReactionLabelGameBestData, 0);
    lv_obj_set_y(ui_ReactionLabelGameBestData, 10);
    lv_obj_set_align(ui_ReactionLabelGameBestData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReactionLabelGameBestData, "--");
    lv_obj_set_style_text_font(ui_ReactionLabelGameBestData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionContainerGameFalse = lv_obj_create(ui_ReactionContainerGameInfo);
    lv_obj_remove_style_all(ui_ReactionContainerGameFalse);
    lv_obj_set_width(ui_ReactionContainerGameFalse, 120);
    lv_obj_set_height(ui_ReactionContainerGameFalse, 50);
    lv_obj_set_x(ui_ReactionContainerGameFalse, 130);
    lv_obj_set_y(ui_ReactionContainerGameFalse, 0);
    lv_obj_set_align(ui_ReactionContainerGameFalse, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReactionContainerGameFalse, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReactionContainerGameFalse, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReactionContainerGameFalse, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionContainerGameFalse, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReactionContainerGameFalse, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReactionContainerGameFalse, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReactionContainerGameFalse, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionLabelGameFalse = lv_label_create(ui_ReactionContainerGameFalse);
    lv_obj_set_width(ui_ReactionLabelGameFalse, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionLabelGameFalse, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReactionLabelGameFalse, 0);
    lv_obj_set_y(ui_ReactionLabelGameFalse, -10);
    lv_obj_set_align(ui_ReactionLabelGameFalse, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReactionLabelGameFalse, "FALSE");
    lv_obj_set_style_text_font(ui_ReactionLabelGameFalse, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionLabelGameFalseData = lv_label_create(ui_ReactionContainerGameFalse);
    lv_obj_set_width(ui_ReactionLabelGameFalseData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionLabelGameFalseData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReactionLabelGameFalseData, 0);
    lv_obj_set_y(ui_ReactionLabelGameFalseData, 10);
    lv_obj_set_align(ui_ReactionLabelGameFalseData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReactionLabelGameFalseData, "0/3");
    lv_obj_set_style_text_font(ui_ReactionLabelGameFalseData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionContainerPlayAreaBackground = lv_obj_create(ui_ReactionScreen);
    lv_obj_remove_style_all(ui_ReactionContainerPlayAreaBackground);
    lv_obj_set_width(ui_ReactionContainerPlayAreaBackground, 400);
    lv_obj_set_height(ui_ReactionContainerPlayAreaBackground, 400);
    lv_obj_set_x(ui_ReactionContainerPlayAreaBackground, 0);
    lv_obj_set_y(ui_ReactionContainerPlayAreaBackground, 30);
    lv_obj_set_align(ui_ReactionContainerPlayAreaBackground, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReactionContainerPlayAreaBackground,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReactionContainerPlayAreaBackground, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReactionContainerPlayAreaBackground, lv_color_hex(0xEED964),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReactionContainerPlayAreaBackground, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReactionContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReactionContainerPlayAreaBackground, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ReactionContainerPlayAreaBackground, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ReactionContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ReactionContainerPlayAreaBackground, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ReactionContainerPlayAreaBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ReactionContainerPlayAreaBackground, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ReactionContainerPlayAreaBackground, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionLabelPlayAreaMainTitle = lv_label_create(ui_ReactionContainerPlayAreaBackground);
    lv_obj_set_width(ui_ReactionLabelPlayAreaMainTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionLabelPlayAreaMainTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReactionLabelPlayAreaMainTitle, 0);
    lv_obj_set_y(ui_ReactionLabelPlayAreaMainTitle, -40);
    lv_obj_set_align(ui_ReactionLabelPlayAreaMainTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReactionLabelPlayAreaMainTitle, "Wait");
    lv_obj_set_style_text_font(ui_ReactionLabelPlayAreaMainTitle, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionLabelPlayAreaSubtitle = lv_label_create(ui_ReactionContainerPlayAreaBackground);
    lv_obj_set_width(ui_ReactionLabelPlayAreaSubtitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionLabelPlayAreaSubtitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReactionLabelPlayAreaSubtitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReactionLabelPlayAreaSubtitle, "Tap when it turns green");
    lv_obj_set_style_text_font(ui_ReactionLabelPlayAreaSubtitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionLabelPlayAreaRound = lv_label_create(ui_ReactionContainerPlayAreaBackground);
    lv_obj_set_width(ui_ReactionLabelPlayAreaRound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionLabelPlayAreaRound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReactionLabelPlayAreaRound, 0);
    lv_obj_set_y(ui_ReactionLabelPlayAreaRound, 80);
    lv_obj_set_align(ui_ReactionLabelPlayAreaRound, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReactionLabelPlayAreaRound, "ROUND 1/5");

    ui_ReactionContainerTools = lv_obj_create(ui_ReactionScreen);
    lv_obj_remove_style_all(ui_ReactionContainerTools);
    lv_obj_set_width(ui_ReactionContainerTools, 80);
    lv_obj_set_height(ui_ReactionContainerTools, 480);
    lv_obj_set_x(ui_ReactionContainerTools, -10);
    lv_obj_set_y(ui_ReactionContainerTools, 0);
    lv_obj_add_flag(ui_ReactionContainerTools, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ReactionContainerTools, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReactionContainerTools, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReactionContainerTools, lv_color_hex(0xB3DFA7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReactionContainerTools, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReactionContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReactionContainerTools, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ReactionContainerTools, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ReactionContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ReactionContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ReactionContainerTools, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ReactionContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ReactionContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionContainerToolExit = lv_obj_create(ui_ReactionContainerTools);
    lv_obj_remove_style_all(ui_ReactionContainerToolExit);
    lv_obj_set_width(ui_ReactionContainerToolExit, 50);
    lv_obj_set_height(ui_ReactionContainerToolExit, 50);
    lv_obj_set_x(ui_ReactionContainerToolExit, 5);
    lv_obj_set_y(ui_ReactionContainerToolExit, 20);
    lv_obj_set_align(ui_ReactionContainerToolExit, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ReactionContainerToolExit, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReactionContainerToolExit, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReactionContainerToolExit, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReactionContainerToolExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReactionContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReactionContainerToolExit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ReactionContainerToolExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ReactionContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ReactionContainerToolExit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ReactionContainerToolExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ReactionContainerToolExit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ReactionContainerToolExit, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionImageToolExit = lv_image_create(ui_ReactionContainerToolExit);
    lv_image_set_src(ui_ReactionImageToolExit, &ui_img_exit_png);
    lv_obj_set_width(ui_ReactionImageToolExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionImageToolExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReactionImageToolExit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReactionImageToolExit, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ReactionImageToolExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ReactionContainerToolQuestion = lv_obj_create(ui_ReactionContainerTools);
    lv_obj_remove_style_all(ui_ReactionContainerToolQuestion);
    lv_obj_set_width(ui_ReactionContainerToolQuestion, 50);
    lv_obj_set_height(ui_ReactionContainerToolQuestion, 50);
    lv_obj_set_x(ui_ReactionContainerToolQuestion, 5);
    lv_obj_set_y(ui_ReactionContainerToolQuestion, 100);
    lv_obj_set_align(ui_ReactionContainerToolQuestion, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ReactionContainerToolQuestion, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReactionContainerToolQuestion, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReactionContainerToolQuestion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReactionContainerToolQuestion, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReactionContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReactionContainerToolQuestion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ReactionContainerToolQuestion, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ReactionContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ReactionContainerToolQuestion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ReactionContainerToolQuestion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ReactionContainerToolQuestion, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ReactionContainerToolQuestion, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionImageToolQuestion = lv_image_create(ui_ReactionContainerToolQuestion);
    lv_image_set_src(ui_ReactionImageToolQuestion, &ui_img_question_png);
    lv_obj_set_width(ui_ReactionImageToolQuestion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionImageToolQuestion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReactionImageToolQuestion, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReactionImageToolQuestion, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ReactionImageToolQuestion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ReactionContainerToolMusic = lv_obj_create(ui_ReactionContainerTools);
    lv_obj_remove_style_all(ui_ReactionContainerToolMusic);
    lv_obj_set_width(ui_ReactionContainerToolMusic, 50);
    lv_obj_set_height(ui_ReactionContainerToolMusic, 50);
    lv_obj_set_x(ui_ReactionContainerToolMusic, 5);
    lv_obj_set_y(ui_ReactionContainerToolMusic, 180);
    lv_obj_set_align(ui_ReactionContainerToolMusic, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ReactionContainerToolMusic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReactionContainerToolMusic, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReactionContainerToolMusic, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReactionContainerToolMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReactionContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReactionContainerToolMusic, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ReactionContainerToolMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ReactionContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ReactionContainerToolMusic, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ReactionContainerToolMusic, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ReactionContainerToolMusic, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ReactionContainerToolMusic, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionImageToolMusic = lv_image_create(ui_ReactionContainerToolMusic);
    lv_image_set_src(ui_ReactionImageToolMusic, &ui_img_music_png);
    lv_obj_set_width(ui_ReactionImageToolMusic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionImageToolMusic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReactionImageToolMusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReactionImageToolMusic, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ReactionImageToolMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ReactionContainerToolRestart = lv_obj_create(ui_ReactionContainerTools);
    lv_obj_remove_style_all(ui_ReactionContainerToolRestart);
    lv_obj_set_width(ui_ReactionContainerToolRestart, 50);
    lv_obj_set_height(ui_ReactionContainerToolRestart, 50);
    lv_obj_set_x(ui_ReactionContainerToolRestart, 5);
    lv_obj_set_y(ui_ReactionContainerToolRestart, 260);
    lv_obj_set_align(ui_ReactionContainerToolRestart, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_ReactionContainerToolRestart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReactionContainerToolRestart, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ReactionContainerToolRestart, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReactionContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReactionContainerToolRestart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReactionContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReactionContainerToolRestart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ReactionContainerToolRestart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ReactionContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ReactionContainerToolRestart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ReactionContainerToolRestart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_ReactionContainerToolRestart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_ReactionContainerToolRestart, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReactionImageToolRestart = lv_image_create(ui_ReactionContainerToolRestart);
    lv_image_set_src(ui_ReactionImageToolRestart, &ui_img_restart_png);
    lv_obj_set_width(ui_ReactionImageToolRestart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReactionImageToolRestart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReactionImageToolRestart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReactionImageToolRestart, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ReactionImageToolRestart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ReactionScreen_screen_destroy(void)
{
    if(ui_ReactionScreen) lv_obj_del(ui_ReactionScreen);

    // NULL screen variables
    ui_ReactionScreen = NULL;
    ui_ReactionContainerToolMenu = NULL;
    ui_ReactionImageToolMenu = NULL;
    ui_ReactionContainerGameInfo = NULL;
    ui_ReactionContainerGameRound = NULL;
    ui_ReactionLabelGameRound = NULL;
    ui_ReactionLabelGameRoundData = NULL;
    ui_ReactionContainerGameBest = NULL;
    ui_ReactionLabelGameBest = NULL;
    ui_ReactionLabelGameBestData = NULL;
    ui_ReactionContainerGameFalse = NULL;
    ui_ReactionLabelGameFalse = NULL;
    ui_ReactionLabelGameFalseData = NULL;
    ui_ReactionContainerPlayAreaBackground = NULL;
    ui_ReactionLabelPlayAreaMainTitle = NULL;
    ui_ReactionLabelPlayAreaSubtitle = NULL;
    ui_ReactionLabelPlayAreaRound = NULL;
    ui_ReactionContainerTools = NULL;
    ui_ReactionContainerToolExit = NULL;
    ui_ReactionImageToolExit = NULL;
    ui_ReactionContainerToolQuestion = NULL;
    ui_ReactionImageToolQuestion = NULL;
    ui_ReactionContainerToolMusic = NULL;
    ui_ReactionImageToolMusic = NULL;
    ui_ReactionContainerToolRestart = NULL;
    ui_ReactionImageToolRestart = NULL;

}
