// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#include "../ui.h"

lv_obj_t * ui_SnakeScreen = NULL;
lv_obj_t * ui_SnakeContainerToolMenu = NULL;
lv_obj_t * ui_SnakeImageToolMenu = NULL;
lv_obj_t * ui_SnakeContainerGameInfo = NULL;
lv_obj_t * ui_SnakeContainerGameScore = NULL;
lv_obj_t * ui_SnakeLabelGameScore = NULL;
lv_obj_t * ui_SnakeLabelGameScoreData = NULL;
lv_obj_t * ui_SnakeContainerGameLength = NULL;
lv_obj_t * ui_SnakeLabelGameLength = NULL;
lv_obj_t * ui_SnakeLabelGameLengthData = NULL;
lv_obj_t * ui_SnakeContainerGameTime = NULL;
lv_obj_t * ui_SnakeLabelGameTime = NULL;
lv_obj_t * ui_SnakeLabelGameTimeData = NULL;
lv_obj_t * ui_SnakeContainerPlayAreaBackground = NULL;
lv_obj_t * ui_SnakeContainerPlayArea = NULL;
lv_obj_t * ui_SnakeContainerTools = NULL;
lv_obj_t * ui_SnakeContainerToolExit = NULL;
lv_obj_t * ui_SnakeImageToolExit = NULL;
lv_obj_t * ui_SnakeContainerToolQuestion = NULL;
lv_obj_t * ui_SnakeImageToolQuestion = NULL;
lv_obj_t * ui_SnakeContainerToolMusic = NULL;
lv_obj_t * ui_SnakeImageToolMusic = NULL;
lv_obj_t * ui_SnakeContainerToolRestart = NULL;
lv_obj_t * ui_SnakeImageToolRestart = NULL;
// event funtions

// build funtions

void ui_SnakeScreen_screen_init(void)
{
    ui_SnakeScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SnakeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SnakeScreen, lv_color_hex(0xE4F3E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeContainerToolMenu = lv_obj_create(ui_SnakeScreen);
    lv_obj_remove_style_all(ui_SnakeContainerToolMenu);
    lv_obj_set_width(ui_SnakeContainerToolMenu, 50);
    lv_obj_set_height(ui_SnakeContainerToolMenu, 50);
    lv_obj_set_x(ui_SnakeContainerToolMenu, 20);
    lv_obj_set_y(ui_SnakeContainerToolMenu, 5);
    lv_obj_remove_flag(ui_SnakeContainerToolMenu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SnakeContainerToolMenu, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnakeContainerToolMenu, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnakeContainerToolMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnakeContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SnakeContainerToolMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SnakeContainerToolMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SnakeContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SnakeContainerToolMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SnakeContainerToolMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SnakeContainerToolMenu, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SnakeContainerToolMenu, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeImageToolMenu = lv_image_create(ui_SnakeContainerToolMenu);
    lv_image_set_src(ui_SnakeImageToolMenu, &ui_img_menu_png);
    lv_obj_set_width(ui_SnakeImageToolMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeImageToolMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SnakeImageToolMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SnakeImageToolMenu, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SnakeImageToolMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SnakeContainerGameInfo = lv_obj_create(ui_SnakeScreen);
    lv_obj_remove_style_all(ui_SnakeContainerGameInfo);
    lv_obj_set_width(ui_SnakeContainerGameInfo, 400);
    lv_obj_set_height(ui_SnakeContainerGameInfo, 60);
    lv_obj_set_x(ui_SnakeContainerGameInfo, 30);
    lv_obj_set_y(ui_SnakeContainerGameInfo, 0);
    lv_obj_set_align(ui_SnakeContainerGameInfo, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_SnakeContainerGameInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SnakeContainerGameScore = lv_obj_create(ui_SnakeContainerGameInfo);
    lv_obj_remove_style_all(ui_SnakeContainerGameScore);
    lv_obj_set_width(ui_SnakeContainerGameScore, 120);
    lv_obj_set_height(ui_SnakeContainerGameScore, 50);
    lv_obj_set_x(ui_SnakeContainerGameScore, -130);
    lv_obj_set_y(ui_SnakeContainerGameScore, 0);
    lv_obj_set_align(ui_SnakeContainerGameScore, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SnakeContainerGameScore, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SnakeContainerGameScore, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnakeContainerGameScore, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeContainerGameScore, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnakeContainerGameScore, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnakeContainerGameScore, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SnakeContainerGameScore, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeLabelGameScore = lv_label_create(ui_SnakeContainerGameScore);
    lv_obj_set_width(ui_SnakeLabelGameScore, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeLabelGameScore, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SnakeLabelGameScore, 0);
    lv_obj_set_y(ui_SnakeLabelGameScore, -10);
    lv_obj_set_align(ui_SnakeLabelGameScore, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SnakeLabelGameScore, "SCORE");
    lv_obj_set_style_text_font(ui_SnakeLabelGameScore, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeLabelGameScoreData = lv_label_create(ui_SnakeContainerGameScore);
    lv_obj_set_width(ui_SnakeLabelGameScoreData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeLabelGameScoreData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SnakeLabelGameScoreData, 0);
    lv_obj_set_y(ui_SnakeLabelGameScoreData, 10);
    lv_obj_set_align(ui_SnakeLabelGameScoreData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SnakeLabelGameScoreData, "0");
    lv_obj_set_style_text_font(ui_SnakeLabelGameScoreData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeContainerGameLength = lv_obj_create(ui_SnakeContainerGameInfo);
    lv_obj_remove_style_all(ui_SnakeContainerGameLength);
    lv_obj_set_width(ui_SnakeContainerGameLength, 120);
    lv_obj_set_height(ui_SnakeContainerGameLength, 50);
    lv_obj_set_align(ui_SnakeContainerGameLength, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SnakeContainerGameLength, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SnakeContainerGameLength, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnakeContainerGameLength, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeContainerGameLength, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnakeContainerGameLength, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnakeContainerGameLength, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SnakeContainerGameLength, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeLabelGameLength = lv_label_create(ui_SnakeContainerGameLength);
    lv_obj_set_width(ui_SnakeLabelGameLength, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeLabelGameLength, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SnakeLabelGameLength, 0);
    lv_obj_set_y(ui_SnakeLabelGameLength, -10);
    lv_obj_set_align(ui_SnakeLabelGameLength, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SnakeLabelGameLength, "LENGTH");
    lv_obj_set_style_text_font(ui_SnakeLabelGameLength, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeLabelGameLengthData = lv_label_create(ui_SnakeContainerGameLength);
    lv_obj_set_width(ui_SnakeLabelGameLengthData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeLabelGameLengthData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SnakeLabelGameLengthData, 0);
    lv_obj_set_y(ui_SnakeLabelGameLengthData, 10);
    lv_obj_set_align(ui_SnakeLabelGameLengthData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SnakeLabelGameLengthData, "3");
    lv_obj_set_style_text_font(ui_SnakeLabelGameLengthData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeContainerGameTime = lv_obj_create(ui_SnakeContainerGameInfo);
    lv_obj_remove_style_all(ui_SnakeContainerGameTime);
    lv_obj_set_width(ui_SnakeContainerGameTime, 120);
    lv_obj_set_height(ui_SnakeContainerGameTime, 50);
    lv_obj_set_x(ui_SnakeContainerGameTime, 130);
    lv_obj_set_y(ui_SnakeContainerGameTime, 0);
    lv_obj_set_align(ui_SnakeContainerGameTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SnakeContainerGameTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SnakeContainerGameTime, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnakeContainerGameTime, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeContainerGameTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnakeContainerGameTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnakeContainerGameTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SnakeContainerGameTime, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeLabelGameTime = lv_label_create(ui_SnakeContainerGameTime);
    lv_obj_set_width(ui_SnakeLabelGameTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeLabelGameTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SnakeLabelGameTime, 0);
    lv_obj_set_y(ui_SnakeLabelGameTime, -10);
    lv_obj_set_align(ui_SnakeLabelGameTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SnakeLabelGameTime, "TIME");
    lv_obj_set_style_text_font(ui_SnakeLabelGameTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeLabelGameTimeData = lv_label_create(ui_SnakeContainerGameTime);
    lv_obj_set_width(ui_SnakeLabelGameTimeData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeLabelGameTimeData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SnakeLabelGameTimeData, 0);
    lv_obj_set_y(ui_SnakeLabelGameTimeData, 10);
    lv_obj_set_align(ui_SnakeLabelGameTimeData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SnakeLabelGameTimeData, "00:01");
    lv_obj_set_style_text_font(ui_SnakeLabelGameTimeData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeContainerPlayAreaBackground = lv_obj_create(ui_SnakeScreen);
    lv_obj_remove_style_all(ui_SnakeContainerPlayAreaBackground);
    lv_obj_set_width(ui_SnakeContainerPlayAreaBackground, 400);
    lv_obj_set_height(ui_SnakeContainerPlayAreaBackground, 400);
    lv_obj_set_x(ui_SnakeContainerPlayAreaBackground, 0);
    lv_obj_set_y(ui_SnakeContainerPlayAreaBackground, 30);
    lv_obj_set_align(ui_SnakeContainerPlayAreaBackground, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SnakeContainerPlayAreaBackground, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SnakeContainerPlayAreaBackground, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnakeContainerPlayAreaBackground, lv_color_hex(0xE3F3D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnakeContainerPlayAreaBackground, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnakeContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SnakeContainerPlayAreaBackground, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SnakeContainerPlayAreaBackground, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SnakeContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SnakeContainerPlayAreaBackground, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SnakeContainerPlayAreaBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SnakeContainerPlayAreaBackground, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SnakeContainerPlayAreaBackground, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeContainerPlayArea = lv_obj_create(ui_SnakeContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_SnakeContainerPlayArea);
    lv_obj_set_width(ui_SnakeContainerPlayArea, 380);
    lv_obj_set_height(ui_SnakeContainerPlayArea, 380);
    lv_obj_set_align(ui_SnakeContainerPlayArea, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SnakeContainerPlayArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SnakeContainerTools = lv_obj_create(ui_SnakeScreen);
    lv_obj_remove_style_all(ui_SnakeContainerTools);
    lv_obj_set_width(ui_SnakeContainerTools, 80);
    lv_obj_set_height(ui_SnakeContainerTools, 480);
    lv_obj_set_x(ui_SnakeContainerTools, -10);
    lv_obj_set_y(ui_SnakeContainerTools, 0);
    lv_obj_add_flag(ui_SnakeContainerTools, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_SnakeContainerTools, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SnakeContainerTools, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnakeContainerTools, lv_color_hex(0xB3DFA7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnakeContainerTools, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnakeContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SnakeContainerTools, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SnakeContainerTools, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SnakeContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SnakeContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SnakeContainerTools, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SnakeContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SnakeContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeContainerToolExit = lv_obj_create(ui_SnakeContainerTools);
    lv_obj_remove_style_all(ui_SnakeContainerToolExit);
    lv_obj_set_width(ui_SnakeContainerToolExit, 50);
    lv_obj_set_height(ui_SnakeContainerToolExit, 50);
    lv_obj_set_x(ui_SnakeContainerToolExit, 5);
    lv_obj_set_y(ui_SnakeContainerToolExit, 20);
    lv_obj_set_align(ui_SnakeContainerToolExit, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_SnakeContainerToolExit, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SnakeContainerToolExit, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnakeContainerToolExit, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnakeContainerToolExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnakeContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SnakeContainerToolExit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SnakeContainerToolExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SnakeContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SnakeContainerToolExit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SnakeContainerToolExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SnakeContainerToolExit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SnakeContainerToolExit, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeImageToolExit = lv_image_create(ui_SnakeContainerToolExit);
    lv_image_set_src(ui_SnakeImageToolExit, &ui_img_exit_png);
    lv_obj_set_width(ui_SnakeImageToolExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeImageToolExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SnakeImageToolExit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SnakeImageToolExit, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SnakeImageToolExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SnakeContainerToolQuestion = lv_obj_create(ui_SnakeContainerTools);
    lv_obj_remove_style_all(ui_SnakeContainerToolQuestion);
    lv_obj_set_width(ui_SnakeContainerToolQuestion, 50);
    lv_obj_set_height(ui_SnakeContainerToolQuestion, 50);
    lv_obj_set_x(ui_SnakeContainerToolQuestion, 5);
    lv_obj_set_y(ui_SnakeContainerToolQuestion, 100);
    lv_obj_set_align(ui_SnakeContainerToolQuestion, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_SnakeContainerToolQuestion, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SnakeContainerToolQuestion, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnakeContainerToolQuestion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnakeContainerToolQuestion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnakeContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SnakeContainerToolQuestion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SnakeContainerToolQuestion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SnakeContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SnakeContainerToolQuestion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SnakeContainerToolQuestion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SnakeContainerToolQuestion, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SnakeContainerToolQuestion, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeImageToolQuestion = lv_image_create(ui_SnakeContainerToolQuestion);
    lv_image_set_src(ui_SnakeImageToolQuestion, &ui_img_question_png);
    lv_obj_set_width(ui_SnakeImageToolQuestion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeImageToolQuestion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SnakeImageToolQuestion, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SnakeImageToolQuestion, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SnakeImageToolQuestion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SnakeContainerToolMusic = lv_obj_create(ui_SnakeContainerTools);
    lv_obj_remove_style_all(ui_SnakeContainerToolMusic);
    lv_obj_set_width(ui_SnakeContainerToolMusic, 50);
    lv_obj_set_height(ui_SnakeContainerToolMusic, 50);
    lv_obj_set_x(ui_SnakeContainerToolMusic, 5);
    lv_obj_set_y(ui_SnakeContainerToolMusic, 180);
    lv_obj_set_align(ui_SnakeContainerToolMusic, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_SnakeContainerToolMusic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SnakeContainerToolMusic, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnakeContainerToolMusic, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnakeContainerToolMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnakeContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SnakeContainerToolMusic, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SnakeContainerToolMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SnakeContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SnakeContainerToolMusic, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SnakeContainerToolMusic, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SnakeContainerToolMusic, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SnakeContainerToolMusic, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeImageToolMusic = lv_image_create(ui_SnakeContainerToolMusic);
    lv_image_set_src(ui_SnakeImageToolMusic, &ui_img_music_png);
    lv_obj_set_width(ui_SnakeImageToolMusic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeImageToolMusic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SnakeImageToolMusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SnakeImageToolMusic, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SnakeImageToolMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SnakeContainerToolRestart = lv_obj_create(ui_SnakeContainerTools);
    lv_obj_remove_style_all(ui_SnakeContainerToolRestart);
    lv_obj_set_width(ui_SnakeContainerToolRestart, 50);
    lv_obj_set_height(ui_SnakeContainerToolRestart, 50);
    lv_obj_set_x(ui_SnakeContainerToolRestart, 5);
    lv_obj_set_y(ui_SnakeContainerToolRestart, 260);
    lv_obj_set_align(ui_SnakeContainerToolRestart, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_SnakeContainerToolRestart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SnakeContainerToolRestart, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnakeContainerToolRestart, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnakeContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnakeContainerToolRestart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnakeContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SnakeContainerToolRestart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SnakeContainerToolRestart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SnakeContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SnakeContainerToolRestart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SnakeContainerToolRestart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_SnakeContainerToolRestart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_SnakeContainerToolRestart, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnakeImageToolRestart = lv_image_create(ui_SnakeContainerToolRestart);
    lv_image_set_src(ui_SnakeImageToolRestart, &ui_img_restart_png);
    lv_obj_set_width(ui_SnakeImageToolRestart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SnakeImageToolRestart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SnakeImageToolRestart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SnakeImageToolRestart, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SnakeImageToolRestart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_SnakeScreen_screen_destroy(void)
{
    if(ui_SnakeScreen) lv_obj_del(ui_SnakeScreen);

    // NULL screen variables
    ui_SnakeScreen = NULL;
    ui_SnakeContainerToolMenu = NULL;
    ui_SnakeImageToolMenu = NULL;
    ui_SnakeContainerGameInfo = NULL;
    ui_SnakeContainerGameScore = NULL;
    ui_SnakeLabelGameScore = NULL;
    ui_SnakeLabelGameScoreData = NULL;
    ui_SnakeContainerGameLength = NULL;
    ui_SnakeLabelGameLength = NULL;
    ui_SnakeLabelGameLengthData = NULL;
    ui_SnakeContainerGameTime = NULL;
    ui_SnakeLabelGameTime = NULL;
    ui_SnakeLabelGameTimeData = NULL;
    ui_SnakeContainerPlayAreaBackground = NULL;
    ui_SnakeContainerPlayArea = NULL;
    ui_SnakeContainerTools = NULL;
    ui_SnakeContainerToolExit = NULL;
    ui_SnakeImageToolExit = NULL;
    ui_SnakeContainerToolQuestion = NULL;
    ui_SnakeImageToolQuestion = NULL;
    ui_SnakeContainerToolMusic = NULL;
    ui_SnakeImageToolMusic = NULL;
    ui_SnakeContainerToolRestart = NULL;
    ui_SnakeImageToolRestart = NULL;

}
