// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#ifndef UI_SNAKESCREEN_H
#define UI_SNAKESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SnakeScreen
extern void ui_SnakeScreen_screen_init(void);
extern void ui_SnakeScreen_screen_destroy(void);
extern lv_obj_t * ui_SnakeScreen;
extern lv_obj_t * ui_SnakeContainerToolMenu;
extern lv_obj_t * ui_SnakeImageToolMenu;
extern lv_obj_t * ui_SnakeContainerGameInfo;
extern lv_obj_t * ui_SnakeContainerGameScore;
extern lv_obj_t * ui_SnakeLabelGameScore;
extern lv_obj_t * ui_SnakeLabelGameScoreData;
extern lv_obj_t * ui_SnakeContainerGameLength;
extern lv_obj_t * ui_SnakeLabelGameLength;
extern lv_obj_t * ui_SnakeLabelGameLengthData;
extern lv_obj_t * ui_SnakeContainerGameTime;
extern lv_obj_t * ui_SnakeLabelGameTime;
extern lv_obj_t * ui_SnakeLabelGameTimeData;
extern lv_obj_t * ui_SnakeContainerPlayAreaBackground;
extern lv_obj_t * ui_SnakeContainerPlayArea;
extern lv_obj_t * ui_SnakeContainerTools;
extern lv_obj_t * ui_SnakeContainerToolExit;
extern lv_obj_t * ui_SnakeImageToolExit;
extern lv_obj_t * ui_SnakeContainerToolQuestion;
extern lv_obj_t * ui_SnakeImageToolQuestion;
extern lv_obj_t * ui_SnakeContainerToolMusic;
extern lv_obj_t * ui_SnakeImageToolMusic;
extern lv_obj_t * ui_SnakeContainerToolRestart;
extern lv_obj_t * ui_SnakeImageToolRestart;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

