// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#ifndef UI_WHACKSCREEN_H
#define UI_WHACKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WhackScreen
extern void ui_WhackScreen_screen_init(void);
extern void ui_WhackScreen_screen_destroy(void);
extern lv_obj_t * ui_WhackScreen;
extern lv_obj_t * ui_WhackContainerToolMenu;
extern lv_obj_t * ui_WhackImageToolMenu;
extern lv_obj_t * ui_WhackContainerGameInfo;
extern lv_obj_t * ui_WhackContainerGameScore;
extern lv_obj_t * ui_WhackLabelGameScore;
extern lv_obj_t * ui_WhackLabelGameScoreData;
extern lv_obj_t * ui_WhackContainerGameCombo;
extern lv_obj_t * ui_WhackLabelGameCombo;
extern lv_obj_t * ui_WhackLabelGameComboData;
extern lv_obj_t * ui_WhackContainerGameTime;
extern lv_obj_t * ui_WhackLabelGameTime;
extern lv_obj_t * ui_WhackLabelGameTimeData;
extern lv_obj_t * ui_WhackContainerPlayAreaBackground;
extern lv_obj_t * ui_WhackContainerPlayAreaHole1;
extern lv_obj_t * ui_WhackImagePlayAreaHole1;
extern lv_obj_t * ui_WhackContainerPlayAreaHole2;
extern lv_obj_t * ui_WhackImagePlayAreaHole2;
extern lv_obj_t * ui_WhackContainerPlayAreaHole3;
extern lv_obj_t * ui_WhackImagePlayAreaHole3;
extern lv_obj_t * ui_WhackContainerPlayAreaHole4;
extern lv_obj_t * ui_WhackImagePlayAreaHole4;
extern lv_obj_t * ui_WhackContainerPlayAreaHole5;
extern lv_obj_t * ui_WhackImagePlayAreaHole5;
extern lv_obj_t * ui_WhackContainerPlayAreaHole6;
extern lv_obj_t * ui_WhackImagePlayAreaHole6;
extern lv_obj_t * ui_WhackContainerPlayAreaHole7;
extern lv_obj_t * ui_WhackImagePlayAreaHole7;
extern lv_obj_t * ui_WhackContainerPlayAreaHole8;
extern lv_obj_t * ui_WhackImagePlayAreaHole8;
extern lv_obj_t * ui_WhackContainerPlayAreaHole9;
extern lv_obj_t * ui_WhackImagePlayAreaHole9;
extern lv_obj_t * ui_WhackContainerTools;
extern lv_obj_t * ui_WhackContainerToolExit;
extern lv_obj_t * ui_WhackImageToolExit;
extern lv_obj_t * ui_WhackContainerToolQuestion;
extern lv_obj_t * ui_WhackImageToolQuestion;
extern lv_obj_t * ui_WhackContainerToolMusic;
extern lv_obj_t * ui_WhackImageToolMusic;
extern lv_obj_t * ui_WhackContainerToolRestart;
extern lv_obj_t * ui_WhackImageToolRestart;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

