// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#include "../ui.h"

lv_obj_t * ui_WhackScreen = NULL;
lv_obj_t * ui_WhackContainerToolMenu = NULL;
lv_obj_t * ui_WhackImageToolMenu = NULL;
lv_obj_t * ui_WhackContainerGameInfo = NULL;
lv_obj_t * ui_WhackContainerGameScore = NULL;
lv_obj_t * ui_WhackLabelGameScore = NULL;
lv_obj_t * ui_WhackLabelGameScoreData = NULL;
lv_obj_t * ui_WhackContainerGameCombo = NULL;
lv_obj_t * ui_WhackLabelGameCombo = NULL;
lv_obj_t * ui_WhackLabelGameComboData = NULL;
lv_obj_t * ui_WhackContainerGameTime = NULL;
lv_obj_t * ui_WhackLabelGameTime = NULL;
lv_obj_t * ui_WhackLabelGameTimeData = NULL;
lv_obj_t * ui_WhackContainerPlayAreaBackground = NULL;
lv_obj_t * ui_WhackContainerPlayAreaHole1 = NULL;
lv_obj_t * ui_WhackImagePlayAreaHole1 = NULL;
lv_obj_t * ui_WhackContainerPlayAreaHole2 = NULL;
lv_obj_t * ui_WhackImagePlayAreaHole2 = NULL;
lv_obj_t * ui_WhackContainerPlayAreaHole3 = NULL;
lv_obj_t * ui_WhackImagePlayAreaHole3 = NULL;
lv_obj_t * ui_WhackContainerPlayAreaHole4 = NULL;
lv_obj_t * ui_WhackImagePlayAreaHole4 = NULL;
lv_obj_t * ui_WhackContainerPlayAreaHole5 = NULL;
lv_obj_t * ui_WhackImagePlayAreaHole5 = NULL;
lv_obj_t * ui_WhackContainerPlayAreaHole6 = NULL;
lv_obj_t * ui_WhackImagePlayAreaHole6 = NULL;
lv_obj_t * ui_WhackContainerPlayAreaHole7 = NULL;
lv_obj_t * ui_WhackImagePlayAreaHole7 = NULL;
lv_obj_t * ui_WhackContainerPlayAreaHole8 = NULL;
lv_obj_t * ui_WhackImagePlayAreaHole8 = NULL;
lv_obj_t * ui_WhackContainerPlayAreaHole9 = NULL;
lv_obj_t * ui_WhackImagePlayAreaHole9 = NULL;
lv_obj_t * ui_WhackContainerTools = NULL;
lv_obj_t * ui_WhackContainerToolExit = NULL;
lv_obj_t * ui_WhackImageToolExit = NULL;
lv_obj_t * ui_WhackContainerToolQuestion = NULL;
lv_obj_t * ui_WhackImageToolQuestion = NULL;
lv_obj_t * ui_WhackContainerToolMusic = NULL;
lv_obj_t * ui_WhackImageToolMusic = NULL;
lv_obj_t * ui_WhackContainerToolRestart = NULL;
lv_obj_t * ui_WhackImageToolRestart = NULL;
// event funtions

// build funtions

void ui_WhackScreen_screen_init(void)
{
    ui_WhackScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WhackScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WhackScreen, lv_color_hex(0xE4EFDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackContainerToolMenu = lv_obj_create(ui_WhackScreen);
    lv_obj_remove_style_all(ui_WhackContainerToolMenu);
    lv_obj_set_width(ui_WhackContainerToolMenu, 50);
    lv_obj_set_height(ui_WhackContainerToolMenu, 50);
    lv_obj_set_x(ui_WhackContainerToolMenu, 20);
    lv_obj_set_y(ui_WhackContainerToolMenu, 5);
    lv_obj_remove_flag(ui_WhackContainerToolMenu, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WhackContainerToolMenu, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WhackContainerToolMenu, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WhackContainerToolMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WhackContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WhackContainerToolMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WhackContainerToolMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WhackContainerToolMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WhackContainerToolMenu, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WhackContainerToolMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_WhackContainerToolMenu, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_WhackContainerToolMenu, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackImageToolMenu = lv_image_create(ui_WhackContainerToolMenu);
    lv_image_set_src(ui_WhackImageToolMenu, &ui_img_menu_png);
    lv_obj_set_width(ui_WhackImageToolMenu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImageToolMenu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImageToolMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WhackImageToolMenu, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImageToolMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerGameInfo = lv_obj_create(ui_WhackScreen);
    lv_obj_remove_style_all(ui_WhackContainerGameInfo);
    lv_obj_set_width(ui_WhackContainerGameInfo, 400);
    lv_obj_set_height(ui_WhackContainerGameInfo, 60);
    lv_obj_set_x(ui_WhackContainerGameInfo, 30);
    lv_obj_set_y(ui_WhackContainerGameInfo, 0);
    lv_obj_set_align(ui_WhackContainerGameInfo, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_WhackContainerGameInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerGameScore = lv_obj_create(ui_WhackContainerGameInfo);
    lv_obj_remove_style_all(ui_WhackContainerGameScore);
    lv_obj_set_width(ui_WhackContainerGameScore, 120);
    lv_obj_set_height(ui_WhackContainerGameScore, 50);
    lv_obj_set_x(ui_WhackContainerGameScore, -130);
    lv_obj_set_y(ui_WhackContainerGameScore, 0);
    lv_obj_set_align(ui_WhackContainerGameScore, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerGameScore, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WhackContainerGameScore, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WhackContainerGameScore, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackContainerGameScore, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WhackContainerGameScore, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WhackContainerGameScore, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WhackContainerGameScore, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackLabelGameScore = lv_label_create(ui_WhackContainerGameScore);
    lv_obj_set_width(ui_WhackLabelGameScore, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackLabelGameScore, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WhackLabelGameScore, 0);
    lv_obj_set_y(ui_WhackLabelGameScore, -10);
    lv_obj_set_align(ui_WhackLabelGameScore, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WhackLabelGameScore, "SCORE");
    lv_obj_set_style_text_font(ui_WhackLabelGameScore, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackLabelGameScoreData = lv_label_create(ui_WhackContainerGameScore);
    lv_obj_set_width(ui_WhackLabelGameScoreData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackLabelGameScoreData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WhackLabelGameScoreData, 0);
    lv_obj_set_y(ui_WhackLabelGameScoreData, 10);
    lv_obj_set_align(ui_WhackLabelGameScoreData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WhackLabelGameScoreData, "0");
    lv_obj_set_style_text_font(ui_WhackLabelGameScoreData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackContainerGameCombo = lv_obj_create(ui_WhackContainerGameInfo);
    lv_obj_remove_style_all(ui_WhackContainerGameCombo);
    lv_obj_set_width(ui_WhackContainerGameCombo, 120);
    lv_obj_set_height(ui_WhackContainerGameCombo, 50);
    lv_obj_set_align(ui_WhackContainerGameCombo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerGameCombo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WhackContainerGameCombo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WhackContainerGameCombo, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackContainerGameCombo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WhackContainerGameCombo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WhackContainerGameCombo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WhackContainerGameCombo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackLabelGameCombo = lv_label_create(ui_WhackContainerGameCombo);
    lv_obj_set_width(ui_WhackLabelGameCombo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackLabelGameCombo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WhackLabelGameCombo, 0);
    lv_obj_set_y(ui_WhackLabelGameCombo, -10);
    lv_obj_set_align(ui_WhackLabelGameCombo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WhackLabelGameCombo, "COMBO");
    lv_obj_set_style_text_font(ui_WhackLabelGameCombo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackLabelGameComboData = lv_label_create(ui_WhackContainerGameCombo);
    lv_obj_set_width(ui_WhackLabelGameComboData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackLabelGameComboData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WhackLabelGameComboData, 0);
    lv_obj_set_y(ui_WhackLabelGameComboData, 10);
    lv_obj_set_align(ui_WhackLabelGameComboData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WhackLabelGameComboData, "0");
    lv_obj_set_style_text_font(ui_WhackLabelGameComboData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackContainerGameTime = lv_obj_create(ui_WhackContainerGameInfo);
    lv_obj_remove_style_all(ui_WhackContainerGameTime);
    lv_obj_set_width(ui_WhackContainerGameTime, 120);
    lv_obj_set_height(ui_WhackContainerGameTime, 50);
    lv_obj_set_x(ui_WhackContainerGameTime, 130);
    lv_obj_set_y(ui_WhackContainerGameTime, 0);
    lv_obj_set_align(ui_WhackContainerGameTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerGameTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WhackContainerGameTime, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WhackContainerGameTime, lv_color_hex(0xFAFBF5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackContainerGameTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WhackContainerGameTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WhackContainerGameTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WhackContainerGameTime, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackLabelGameTime = lv_label_create(ui_WhackContainerGameTime);
    lv_obj_set_width(ui_WhackLabelGameTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackLabelGameTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WhackLabelGameTime, 0);
    lv_obj_set_y(ui_WhackLabelGameTime, -10);
    lv_obj_set_align(ui_WhackLabelGameTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WhackLabelGameTime, "TIME");
    lv_obj_set_style_text_font(ui_WhackLabelGameTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackLabelGameTimeData = lv_label_create(ui_WhackContainerGameTime);
    lv_obj_set_width(ui_WhackLabelGameTimeData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackLabelGameTimeData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WhackLabelGameTimeData, 0);
    lv_obj_set_y(ui_WhackLabelGameTimeData, 10);
    lv_obj_set_align(ui_WhackLabelGameTimeData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WhackLabelGameTimeData, "0s");
    lv_obj_set_style_text_font(ui_WhackLabelGameTimeData, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackContainerPlayAreaBackground = lv_obj_create(ui_WhackScreen);
    lv_obj_remove_style_all(ui_WhackContainerPlayAreaBackground);
    lv_obj_set_width(ui_WhackContainerPlayAreaBackground, 400);
    lv_obj_set_height(ui_WhackContainerPlayAreaBackground, 400);
    lv_obj_set_x(ui_WhackContainerPlayAreaBackground, 0);
    lv_obj_set_y(ui_WhackContainerPlayAreaBackground, 30);
    lv_obj_set_align(ui_WhackContainerPlayAreaBackground, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerPlayAreaBackground, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WhackContainerPlayAreaBackground, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WhackContainerPlayAreaBackground, lv_color_hex(0xE3F3D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WhackContainerPlayAreaBackground, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WhackContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WhackContainerPlayAreaBackground, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WhackContainerPlayAreaBackground, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WhackContainerPlayAreaBackground, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WhackContainerPlayAreaBackground, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WhackContainerPlayAreaBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_WhackContainerPlayAreaBackground, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_WhackContainerPlayAreaBackground, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackContainerPlayAreaHole1 = lv_obj_create(ui_WhackContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_WhackContainerPlayAreaHole1);
    lv_obj_set_width(ui_WhackContainerPlayAreaHole1, 100);
    lv_obj_set_height(ui_WhackContainerPlayAreaHole1, 80);
    lv_obj_set_x(ui_WhackContainerPlayAreaHole1, -130);
    lv_obj_set_y(ui_WhackContainerPlayAreaHole1, -130);
    lv_obj_set_align(ui_WhackContainerPlayAreaHole1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerPlayAreaHole1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackImagePlayAreaHole1 = lv_image_create(ui_WhackContainerPlayAreaHole1);
    lv_image_set_src(ui_WhackImagePlayAreaHole1, &ui_img_hole_png);
    lv_obj_set_width(ui_WhackImagePlayAreaHole1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImagePlayAreaHole1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImagePlayAreaHole1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_WhackImagePlayAreaHole1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImagePlayAreaHole1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerPlayAreaHole2 = lv_obj_create(ui_WhackContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_WhackContainerPlayAreaHole2);
    lv_obj_set_width(ui_WhackContainerPlayAreaHole2, 100);
    lv_obj_set_height(ui_WhackContainerPlayAreaHole2, 80);
    lv_obj_set_x(ui_WhackContainerPlayAreaHole2, 0);
    lv_obj_set_y(ui_WhackContainerPlayAreaHole2, -130);
    lv_obj_set_align(ui_WhackContainerPlayAreaHole2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerPlayAreaHole2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackImagePlayAreaHole2 = lv_image_create(ui_WhackContainerPlayAreaHole2);
    lv_image_set_src(ui_WhackImagePlayAreaHole2, &ui_img_hole_png);
    lv_obj_set_width(ui_WhackImagePlayAreaHole2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImagePlayAreaHole2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImagePlayAreaHole2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_WhackImagePlayAreaHole2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImagePlayAreaHole2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerPlayAreaHole3 = lv_obj_create(ui_WhackContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_WhackContainerPlayAreaHole3);
    lv_obj_set_width(ui_WhackContainerPlayAreaHole3, 100);
    lv_obj_set_height(ui_WhackContainerPlayAreaHole3, 80);
    lv_obj_set_x(ui_WhackContainerPlayAreaHole3, 130);
    lv_obj_set_y(ui_WhackContainerPlayAreaHole3, -130);
    lv_obj_set_align(ui_WhackContainerPlayAreaHole3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerPlayAreaHole3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackImagePlayAreaHole3 = lv_image_create(ui_WhackContainerPlayAreaHole3);
    lv_image_set_src(ui_WhackImagePlayAreaHole3, &ui_img_hole_png);
    lv_obj_set_width(ui_WhackImagePlayAreaHole3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImagePlayAreaHole3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImagePlayAreaHole3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_WhackImagePlayAreaHole3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImagePlayAreaHole3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerPlayAreaHole4 = lv_obj_create(ui_WhackContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_WhackContainerPlayAreaHole4);
    lv_obj_set_width(ui_WhackContainerPlayAreaHole4, 100);
    lv_obj_set_height(ui_WhackContainerPlayAreaHole4, 80);
    lv_obj_set_x(ui_WhackContainerPlayAreaHole4, -130);
    lv_obj_set_y(ui_WhackContainerPlayAreaHole4, 0);
    lv_obj_set_align(ui_WhackContainerPlayAreaHole4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerPlayAreaHole4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackImagePlayAreaHole4 = lv_image_create(ui_WhackContainerPlayAreaHole4);
    lv_image_set_src(ui_WhackImagePlayAreaHole4, &ui_img_hole_png);
    lv_obj_set_width(ui_WhackImagePlayAreaHole4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImagePlayAreaHole4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImagePlayAreaHole4, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_WhackImagePlayAreaHole4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImagePlayAreaHole4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerPlayAreaHole5 = lv_obj_create(ui_WhackContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_WhackContainerPlayAreaHole5);
    lv_obj_set_width(ui_WhackContainerPlayAreaHole5, 100);
    lv_obj_set_height(ui_WhackContainerPlayAreaHole5, 80);
    lv_obj_set_align(ui_WhackContainerPlayAreaHole5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerPlayAreaHole5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackImagePlayAreaHole5 = lv_image_create(ui_WhackContainerPlayAreaHole5);
    lv_image_set_src(ui_WhackImagePlayAreaHole5, &ui_img_hole_png);
    lv_obj_set_width(ui_WhackImagePlayAreaHole5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImagePlayAreaHole5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImagePlayAreaHole5, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_WhackImagePlayAreaHole5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImagePlayAreaHole5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerPlayAreaHole6 = lv_obj_create(ui_WhackContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_WhackContainerPlayAreaHole6);
    lv_obj_set_width(ui_WhackContainerPlayAreaHole6, 100);
    lv_obj_set_height(ui_WhackContainerPlayAreaHole6, 80);
    lv_obj_set_x(ui_WhackContainerPlayAreaHole6, 130);
    lv_obj_set_y(ui_WhackContainerPlayAreaHole6, 0);
    lv_obj_set_align(ui_WhackContainerPlayAreaHole6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerPlayAreaHole6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackImagePlayAreaHole6 = lv_image_create(ui_WhackContainerPlayAreaHole6);
    lv_image_set_src(ui_WhackImagePlayAreaHole6, &ui_img_hole_png);
    lv_obj_set_width(ui_WhackImagePlayAreaHole6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImagePlayAreaHole6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImagePlayAreaHole6, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_WhackImagePlayAreaHole6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImagePlayAreaHole6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerPlayAreaHole7 = lv_obj_create(ui_WhackContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_WhackContainerPlayAreaHole7);
    lv_obj_set_width(ui_WhackContainerPlayAreaHole7, 100);
    lv_obj_set_height(ui_WhackContainerPlayAreaHole7, 80);
    lv_obj_set_x(ui_WhackContainerPlayAreaHole7, -130);
    lv_obj_set_y(ui_WhackContainerPlayAreaHole7, 130);
    lv_obj_set_align(ui_WhackContainerPlayAreaHole7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerPlayAreaHole7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackImagePlayAreaHole7 = lv_image_create(ui_WhackContainerPlayAreaHole7);
    lv_image_set_src(ui_WhackImagePlayAreaHole7, &ui_img_hole_png);
    lv_obj_set_width(ui_WhackImagePlayAreaHole7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImagePlayAreaHole7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImagePlayAreaHole7, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_WhackImagePlayAreaHole7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImagePlayAreaHole7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerPlayAreaHole8 = lv_obj_create(ui_WhackContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_WhackContainerPlayAreaHole8);
    lv_obj_set_width(ui_WhackContainerPlayAreaHole8, 100);
    lv_obj_set_height(ui_WhackContainerPlayAreaHole8, 80);
    lv_obj_set_x(ui_WhackContainerPlayAreaHole8, 0);
    lv_obj_set_y(ui_WhackContainerPlayAreaHole8, 130);
    lv_obj_set_align(ui_WhackContainerPlayAreaHole8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerPlayAreaHole8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackImagePlayAreaHole8 = lv_image_create(ui_WhackContainerPlayAreaHole8);
    lv_image_set_src(ui_WhackImagePlayAreaHole8, &ui_img_hole_png);
    lv_obj_set_width(ui_WhackImagePlayAreaHole8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImagePlayAreaHole8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImagePlayAreaHole8, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_WhackImagePlayAreaHole8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImagePlayAreaHole8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerPlayAreaHole9 = lv_obj_create(ui_WhackContainerPlayAreaBackground);
    lv_obj_remove_style_all(ui_WhackContainerPlayAreaHole9);
    lv_obj_set_width(ui_WhackContainerPlayAreaHole9, 100);
    lv_obj_set_height(ui_WhackContainerPlayAreaHole9, 80);
    lv_obj_set_x(ui_WhackContainerPlayAreaHole9, 130);
    lv_obj_set_y(ui_WhackContainerPlayAreaHole9, 130);
    lv_obj_set_align(ui_WhackContainerPlayAreaHole9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WhackContainerPlayAreaHole9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackImagePlayAreaHole9 = lv_image_create(ui_WhackContainerPlayAreaHole9);
    lv_image_set_src(ui_WhackImagePlayAreaHole9, &ui_img_hole_png);
    lv_obj_set_width(ui_WhackImagePlayAreaHole9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImagePlayAreaHole9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImagePlayAreaHole9, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_WhackImagePlayAreaHole9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImagePlayAreaHole9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerTools = lv_obj_create(ui_WhackScreen);
    lv_obj_remove_style_all(ui_WhackContainerTools);
    lv_obj_set_width(ui_WhackContainerTools, 80);
    lv_obj_set_height(ui_WhackContainerTools, 480);
    lv_obj_set_x(ui_WhackContainerTools, -10);
    lv_obj_set_y(ui_WhackContainerTools, 0);
    lv_obj_add_flag(ui_WhackContainerTools, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_WhackContainerTools, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WhackContainerTools, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WhackContainerTools, lv_color_hex(0xB3DFA7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WhackContainerTools, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WhackContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WhackContainerTools, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WhackContainerTools, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WhackContainerTools, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WhackContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WhackContainerTools, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_WhackContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_WhackContainerTools, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackContainerToolExit = lv_obj_create(ui_WhackContainerTools);
    lv_obj_remove_style_all(ui_WhackContainerToolExit);
    lv_obj_set_width(ui_WhackContainerToolExit, 50);
    lv_obj_set_height(ui_WhackContainerToolExit, 50);
    lv_obj_set_x(ui_WhackContainerToolExit, 5);
    lv_obj_set_y(ui_WhackContainerToolExit, 20);
    lv_obj_set_align(ui_WhackContainerToolExit, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_WhackContainerToolExit, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WhackContainerToolExit, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WhackContainerToolExit, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WhackContainerToolExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WhackContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WhackContainerToolExit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WhackContainerToolExit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WhackContainerToolExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WhackContainerToolExit, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WhackContainerToolExit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_WhackContainerToolExit, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_WhackContainerToolExit, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackImageToolExit = lv_image_create(ui_WhackContainerToolExit);
    lv_image_set_src(ui_WhackImageToolExit, &ui_img_exit_png);
    lv_obj_set_width(ui_WhackImageToolExit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImageToolExit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImageToolExit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WhackImageToolExit, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImageToolExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerToolQuestion = lv_obj_create(ui_WhackContainerTools);
    lv_obj_remove_style_all(ui_WhackContainerToolQuestion);
    lv_obj_set_width(ui_WhackContainerToolQuestion, 50);
    lv_obj_set_height(ui_WhackContainerToolQuestion, 50);
    lv_obj_set_x(ui_WhackContainerToolQuestion, 5);
    lv_obj_set_y(ui_WhackContainerToolQuestion, 100);
    lv_obj_set_align(ui_WhackContainerToolQuestion, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_WhackContainerToolQuestion, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WhackContainerToolQuestion, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WhackContainerToolQuestion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WhackContainerToolQuestion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WhackContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WhackContainerToolQuestion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WhackContainerToolQuestion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WhackContainerToolQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WhackContainerToolQuestion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WhackContainerToolQuestion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_WhackContainerToolQuestion, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_WhackContainerToolQuestion, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackImageToolQuestion = lv_image_create(ui_WhackContainerToolQuestion);
    lv_image_set_src(ui_WhackImageToolQuestion, &ui_img_question_png);
    lv_obj_set_width(ui_WhackImageToolQuestion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImageToolQuestion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImageToolQuestion, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WhackImageToolQuestion, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImageToolQuestion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerToolMusic = lv_obj_create(ui_WhackContainerTools);
    lv_obj_remove_style_all(ui_WhackContainerToolMusic);
    lv_obj_set_width(ui_WhackContainerToolMusic, 50);
    lv_obj_set_height(ui_WhackContainerToolMusic, 50);
    lv_obj_set_x(ui_WhackContainerToolMusic, 5);
    lv_obj_set_y(ui_WhackContainerToolMusic, 180);
    lv_obj_set_align(ui_WhackContainerToolMusic, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_WhackContainerToolMusic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WhackContainerToolMusic, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WhackContainerToolMusic, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WhackContainerToolMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WhackContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WhackContainerToolMusic, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WhackContainerToolMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WhackContainerToolMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WhackContainerToolMusic, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WhackContainerToolMusic, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_WhackContainerToolMusic, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_WhackContainerToolMusic, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackImageToolMusic = lv_image_create(ui_WhackContainerToolMusic);
    lv_image_set_src(ui_WhackImageToolMusic, &ui_img_music_png);
    lv_obj_set_width(ui_WhackImageToolMusic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImageToolMusic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImageToolMusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WhackImageToolMusic, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImageToolMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WhackContainerToolRestart = lv_obj_create(ui_WhackContainerTools);
    lv_obj_remove_style_all(ui_WhackContainerToolRestart);
    lv_obj_set_width(ui_WhackContainerToolRestart, 50);
    lv_obj_set_height(ui_WhackContainerToolRestart, 50);
    lv_obj_set_x(ui_WhackContainerToolRestart, 5);
    lv_obj_set_y(ui_WhackContainerToolRestart, 260);
    lv_obj_set_align(ui_WhackContainerToolRestart, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_WhackContainerToolRestart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WhackContainerToolRestart, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WhackContainerToolRestart, lv_color_hex(0xFEFDF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WhackContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WhackContainerToolRestart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WhackContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WhackContainerToolRestart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WhackContainerToolRestart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WhackContainerToolRestart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WhackContainerToolRestart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WhackContainerToolRestart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_WhackContainerToolRestart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_WhackContainerToolRestart, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhackImageToolRestart = lv_image_create(ui_WhackContainerToolRestart);
    lv_image_set_src(ui_WhackImageToolRestart, &ui_img_restart_png);
    lv_obj_set_width(ui_WhackImageToolRestart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhackImageToolRestart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WhackImageToolRestart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WhackImageToolRestart, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WhackImageToolRestart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_WhackScreen_screen_destroy(void)
{
    if(ui_WhackScreen) lv_obj_del(ui_WhackScreen);

    // NULL screen variables
    ui_WhackScreen = NULL;
    ui_WhackContainerToolMenu = NULL;
    ui_WhackImageToolMenu = NULL;
    ui_WhackContainerGameInfo = NULL;
    ui_WhackContainerGameScore = NULL;
    ui_WhackLabelGameScore = NULL;
    ui_WhackLabelGameScoreData = NULL;
    ui_WhackContainerGameCombo = NULL;
    ui_WhackLabelGameCombo = NULL;
    ui_WhackLabelGameComboData = NULL;
    ui_WhackContainerGameTime = NULL;
    ui_WhackLabelGameTime = NULL;
    ui_WhackLabelGameTimeData = NULL;
    ui_WhackContainerPlayAreaBackground = NULL;
    ui_WhackContainerPlayAreaHole1 = NULL;
    ui_WhackImagePlayAreaHole1 = NULL;
    ui_WhackContainerPlayAreaHole2 = NULL;
    ui_WhackImagePlayAreaHole2 = NULL;
    ui_WhackContainerPlayAreaHole3 = NULL;
    ui_WhackImagePlayAreaHole3 = NULL;
    ui_WhackContainerPlayAreaHole4 = NULL;
    ui_WhackImagePlayAreaHole4 = NULL;
    ui_WhackContainerPlayAreaHole5 = NULL;
    ui_WhackImagePlayAreaHole5 = NULL;
    ui_WhackContainerPlayAreaHole6 = NULL;
    ui_WhackImagePlayAreaHole6 = NULL;
    ui_WhackContainerPlayAreaHole7 = NULL;
    ui_WhackImagePlayAreaHole7 = NULL;
    ui_WhackContainerPlayAreaHole8 = NULL;
    ui_WhackImagePlayAreaHole8 = NULL;
    ui_WhackContainerPlayAreaHole9 = NULL;
    ui_WhackImagePlayAreaHole9 = NULL;
    ui_WhackContainerTools = NULL;
    ui_WhackContainerToolExit = NULL;
    ui_WhackImageToolExit = NULL;
    ui_WhackContainerToolQuestion = NULL;
    ui_WhackImageToolQuestion = NULL;
    ui_WhackContainerToolMusic = NULL;
    ui_WhackImageToolMusic = NULL;
    ui_WhackContainerToolRestart = NULL;
    ui_WhackImageToolRestart = NULL;

}
