// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: vibecoding

#ifndef _VIBECODING_UI_H
#define _VIBECODING_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_SnakeScreen.h"
#include "screens/ui_ReactionScreen.h"
#include "screens/ui_WhackScreen.h"
#include "screens/ui_GameScreen.h"
#include "screens/ui_NonogramScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_menu_png);    // assets/Menu.png
LV_IMG_DECLARE(ui_img_exit_png);    // assets/Exit.png
LV_IMG_DECLARE(ui_img_question_png);    // assets/Question.png
LV_IMG_DECLARE(ui_img_music_png);    // assets/Music.png
LV_IMG_DECLARE(ui_img_restart_png);    // assets/Restart.png
LV_IMG_DECLARE(ui_img_bomb_png);    // assets/bomb.png
LV_IMG_DECLARE(ui_img_hole_png);    // assets/hole.png
LV_IMG_DECLARE(ui_img_mole_png);    // assets/mole.png
LV_IMG_DECLARE(ui_img_snake_png);    // assets/snack.png
LV_IMG_DECLARE(ui_img_reaction_png);    // assets/reaction.png
LV_IMG_DECLARE(ui_img_whack_png);    // assets/whack.png
LV_IMG_DECLARE(ui_img_nonogram_png);    // assets/Nonogram.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
